### ISSUE TITLE
Connection drop error message from service

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-ai-connect-service#32]
The error message is seen occasionally while using the service with the VSCode extension and it is not always reproducible. The error will result in a timeout message to the user on the extension side. The default request timeout is 5 seconds for extension
Logs:
```
docker-compose-django-1  | DEBUG:Resetting dropped connection: wisdom-wisdom-dev.apps.dev.wisdom.testing.ansible.com
```

**Comment by gebhardtr** [comment]
@ganeshrn closing this one as it's pretty old and may already be fixed. Please reopen if you're still seeing the issue and thanks again for reporting it!
